services:
  backend:
    build: ./backend
    env_file: .env
    environment:
      ASSETS_DIR: /assets
    volumes:
      - ${ASSETS_DIR}:/assets:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_PROJECT_NAME: ${VITE_PROJECT_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs/paracosm-vtt.pem:/etc/ssl/certs/paracosm-vtt.pem:ro
      - /etc/ssl/private/paracosm-vtt.key:/etc/ssl/private/paracosm-vtt.key:ro
    depends_on:
      - backend
    restart: unless-stopped
