services:
  frontend:
    environment:
      ORIGIN: ${ORIGIN}

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/certs/paracosm-vtt.pem:/etc/ssl/certs/paracosm-vtt.pem:ro
      - /etc/ssl/private/paracosm-vtt.key:/etc/ssl/private/paracosm-vtt.key:ro
